# Generated by Django 3.1.4 on 2021-01-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blogs', '0003_alter_email_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
