# Generated by Django 3.1.4 on 2021-01-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blogs', '0005_alter_username_first_name_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
    ]
